#全局端口定义server:
# 全局字符集设置
spring:
  aop:
    proxy-target-class: true
server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

